[build]
  command = "cd netlify/functions && npm install"
  publish = "frontend"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  
# Redirigir todas las llamadas /api/* a la función serverless
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
